#!/usr/bin/env bash
# ══════════════════════════════════════════════════════════════════
#  GaragePro — One-Command Installer for Raspberry Pi (3B+/4B/5)
# ══════════════════════════════════════════════════════════════════
#
#  IMPORTANT: Rename this file to install-garagepro.sh before use:
#      mv deploy/install-garagepro.txt deploy/install-garagepro.sh
#      chmod +x deploy/install-garagepro.sh
#      sudo bash deploy/install-garagepro.sh
#
#  What it does:
#   1. Installs system dependencies (Python 3, pip, Tesseract OCR)
#   2. Creates a dedicated 'garagepro' system user
#   3. Copies the app to /opt/garagepro
#   4. Creates a Python virtual environment + installs pip packages
#   5. Initializes the SQLite database with demo data
#   6. Installs and starts a systemd service
#   7. Configures zram swap (optional, for Pi models with <=1 GB RAM)
#   8. Sets up daily automatic backups at 03:00
#
#  After install, open http://<pi-ip>:8000 in your browser.
#  Default login:  admin / admin123  (change immediately!)
# ══════════════════════════════════════════════════════════════════

set -euo pipefail

APP_NAME="garagepro"
APP_DIR="/opt/${APP_NAME}"
APP_USER="garagepro"
APP_PORT=8000
SERVICE_FILE="/etc/systemd/system/${APP_NAME}.service"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

banner() {
    echo ""
    echo -e "${CYAN}╔══════════════════════════════════════════════╗${NC}"
    echo -e "${CYAN}║          🔧  GaragePro  Installer            ║${NC}"
    echo -e "${CYAN}║    Car Service Management for Raspberry Pi   ║${NC}"
    echo -e "${CYAN}╚══════════════════════════════════════════════╝${NC}"
    echo ""
}

info()  { echo -e "${GREEN}[✓]${NC} $1"; }
warn()  { echo -e "${YELLOW}[!]${NC} $1"; }
fail()  { echo -e "${RED}[✗]${NC} $1"; exit 1; }
step()  { echo -e "\n${CYAN}──── $1 ────${NC}"; }

# ── Pre-checks ──────────────────────────────────────────────────
banner

if [[ $EUID -ne 0 ]]; then
    fail "This script must be run as root (use sudo)."
fi

if [[ ! -f "$PROJECT_ROOT/serve.py" ]]; then
    fail "Cannot find serve.py in $PROJECT_ROOT — run from the project root."
fi

PI_MODEL="unknown"
if [[ -f /proc/device-tree/model ]]; then
    PI_MODEL=$(tr -d '\0' < /proc/device-tree/model)
fi
info "Detected: ${PI_MODEL}"

TOTAL_RAM_MB=$(awk '/MemTotal/ {printf "%d", $2/1024}' /proc/meminfo)
info "RAM: ${TOTAL_RAM_MB} MB"

# ── Step 1: System packages ─────────────────────────────────────
step "Installing system dependencies"

apt-get update -qq
apt-get install -y -qq \
    python3 python3-venv python3-pip python3-dev \
    tesseract-ocr tesseract-ocr-srp \
    libjpeg-dev libopenjp2-7 libffi-dev \
    zlib1g-dev libfreetype6-dev \
    sqlite3 rsync \
    > /dev/null 2>&1

info "System packages installed"

# ── Step 2: Create system user ──────────────────────────────────
step "Setting up GaragePro user"

if id "$APP_USER" &>/dev/null; then
    info "User '${APP_USER}' already exists"
else
    useradd --system --shell /usr/sbin/nologin --home-dir "$APP_DIR" "$APP_USER"
    info "Created system user '${APP_USER}'"
fi

# ── Step 3: Copy application ────────────────────────────────────
step "Deploying application to ${APP_DIR}"

mkdir -p "$APP_DIR"

rsync -a --delete \
    --exclude='.git' \
    --exclude='.vio' \
    --exclude='__pycache__' \
    --exclude='*.pyc' \
    --exclude='venv' \
    --exclude='instance' \
    --exclude='deploy' \
    --exclude='.env' \
    "$PROJECT_ROOT/" "$APP_DIR/"

mkdir -p "$APP_DIR/instance"
mkdir -p "$APP_DIR/instance/uploads"
mkdir -p "$APP_DIR/instance/backups"

info "Application files deployed"

# ── Step 4: Python virtual environment ──────────────────────────
step "Creating Python virtual environment"

if [[ ! -d "$APP_DIR/venv" ]]; then
    python3 -m venv "$APP_DIR/venv"
    info "Virtual environment created"
else
    info "Virtual environment already exists — upgrading packages"
fi

"$APP_DIR/venv/bin/pip" install --upgrade pip -q
"$APP_DIR/venv/bin/pip" install -r "$APP_DIR/requirements.txt" -q

info "Python dependencies installed"

# ── Step 5: Environment file ────────────────────────────────────
step "Configuring environment"

if [[ ! -f "$APP_DIR/.env" ]]; then
    SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))")
    cat > "$APP_DIR/.env" <<ENVEOF
# GaragePro configuration — generated by installer
SECRET_KEY=${SECRET_KEY}
PORT=${APP_PORT}
HOST=0.0.0.0
THREADS=4
TESSDATA_PREFIX=/usr/share/tesseract-ocr/5/tessdata
ENVEOF
    info "Generated .env with random SECRET_KEY"
else
    warn ".env already exists — keeping existing configuration"
fi

# ── Step 6: Initialize database ─────────────────────────────────
step "Initializing database"

if [[ ! -f "$APP_DIR/instance/carservice.db" ]]; then
    cd "$APP_DIR"
    "$APP_DIR/venv/bin/python" init_db.py --reset
    info "Empty database created"
    info "Register the first account — it becomes MODERATOR automatically"
else
    warn "Database already exists — skipping initialization"
fi

# ── Step 7: Fix ownership ───────────────────────────────────────
chown -R "$APP_USER:$APP_USER" "$APP_DIR"
chmod 750 "$APP_DIR"
chmod 640 "$APP_DIR/.env"

info "Permissions set"

# ── Step 8: Install systemd service ─────────────────────────────
step "Installing systemd service"

cat > "$SERVICE_FILE" <<SVCEOF
[Unit]
Description=GaragePro — Car Service Management Platform
After=network.target
StartLimitIntervalSec=60
StartLimitBurst=5

[Service]
Type=simple
User=${APP_USER}
Group=${APP_USER}
WorkingDirectory=${APP_DIR}
ExecStart=${APP_DIR}/venv/bin/python serve.py
Restart=on-failure
RestartSec=5

Environment=PORT=${APP_PORT}
Environment=HOST=0.0.0.0
Environment=THREADS=4
EnvironmentFile=-${APP_DIR}/.env

StandardOutput=journal
StandardError=journal
SyslogIdentifier=${APP_NAME}

ProtectSystem=full
ProtectHome=true
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
SVCEOF

systemctl daemon-reload
systemctl enable "$APP_NAME"
systemctl start "$APP_NAME"

info "Systemd service installed and started"

# ── Step 9: Zram swap (for low-RAM Pi models) ──────────────────
if [[ $TOTAL_RAM_MB -le 1024 ]]; then
    step "Configuring zram swap (recommended for ${TOTAL_RAM_MB} MB RAM)"

    if ! modprobe zram 2>/dev/null; then
        warn "zram module not available — skipping"
    else
        if [[ ! -f /etc/systemd/system/zram-swap.service ]]; then
            ZRAM_SIZE=$((TOTAL_RAM_MB / 2))
            cat > /etc/systemd/system/zram-swap.service <<ZRAMEOF
[Unit]
Description=zram swap for GaragePro
After=local-fs.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/bin/bash -c 'modprobe zram && echo ${ZRAM_SIZE}M > /sys/block/zram0/disksize && mkswap /dev/zram0 && swapon -p 10 /dev/zram0'
ExecStop=/bin/bash -c 'swapoff /dev/zram0 && echo 1 > /sys/block/zram0/reset'

[Install]
WantedBy=multi-user.target
ZRAMEOF
            systemctl daemon-reload
            systemctl enable zram-swap
            systemctl start zram-swap
            info "zram swap (${ZRAM_SIZE} MB) enabled"
        else
            info "zram swap already configured"
        fi
    fi
else
    info "RAM is ${TOTAL_RAM_MB} MB — zram swap not needed"
fi

# ── Step 10: Daily backup cron ──────────────────────────────────
step "Setting up daily backups"

CRON_LINE="0 3 * * * ${APP_USER} cd ${APP_DIR} && ${APP_DIR}/venv/bin/python backup.py >> /var/log/garagepro-backup.log 2>&1"

if [[ ! -f /etc/cron.d/garagepro-backup ]]; then
    echo "$CRON_LINE" > /etc/cron.d/garagepro-backup
    chmod 644 /etc/cron.d/garagepro-backup
    info "Daily backup at 03:00 configured"
else
    warn "Backup cron already exists"
fi

# ── Done! ───────────────────────────────────────────────────────
sleep 2
LOCAL_IP=$(hostname -I | awk '{print $1}')

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║       🎉  GaragePro is running!               ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  Open in browser:  ${CYAN}http://${LOCAL_IP}:${APP_PORT}${NC}"
echo -e "  First run:         ${YELLOW}register an account${NC} — it becomes MODERATOR"
echo ""
echo -e "  Useful commands:"
echo -e "    ${CYAN}sudo systemctl status garagepro${NC}    — check status"
echo -e "    ${CYAN}sudo systemctl restart garagepro${NC}   — restart"
echo -e "    ${CYAN}sudo journalctl -u garagepro -f${NC}    — live logs"
echo -e "    ${CYAN}sudo bash deploy/uninstall-garagepro.sh${NC}  — remove"
echo ""
